### ISSUE TITLE
Deep watch options

### ISSUE THREAD

**Issue by ochi51** [xkeshi/vue-barcode#5]
https://github.com/xkeshi/vue-barcode/blob/master/src/index.js#L45-L47

I think it would be better to add the `deep` option like this.

```.javascript
    options() {
      deep: true,
      handler() {
        this.generate();
      }
    },
```

**Comment by fengyuanchen** [comment]
Thanks for your suggestion, this repo had been deprecated , I have developed another one with the same APIs: https://github.com/fengyuanchen/vue-barcode
